on: issue_comment
name: Issue Comments
jobs:
  check_comments:
    name: Check comments for /test
    runs-on: ubuntu-latest
    steps:
      - name: Check for Command
        id: command
        #uses: xt0rted/slash-command-action@v1
        uses: maxkomarychev/oction-merge-pull-request@v0.7.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull_number: 'true'
          command: test
      - name:
        run: |
          echo ${{ steps.my_step_id.outputs.id }}
          echo ${{ steps.my_step_id.outputs.number }}
            
